import React, { useState, useEffect } from 'react';
import { supabase } from '../supabaseClient';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const Order = () => {
  // Database State
  const [replenishList, setReplenishList] = useState([]);
  const [loading, setLoading] = useState(true);
  const [statusMessage, setStatusMessage] = useState('');

  // Interactive Reorder Quantities State Map (Key: productName, Value: quantity to order)
  const [reorderQuantities, setReorderQuantities] = useState({});

  // Critical Configuration line
  const REPLENISH_THRESHOLD = 10; 

  useEffect(() => {
    async function fetchDepletedStock() {
      try {
        setLoading(true);
        const { data, error } = await supabase
          .from('Stock')
          .select('*')
          .lte('qty', REPLENISH_THRESHOLD)
          .order('qty', { ascending: true });

        if (error) throw error;
        
        setReplenishList(data || []);

        // Initialize reorder quantities state map with baseline targets
        const initialQuantities = {};
        data?.forEach(item => {
          // Default baseline calculation: target to reach 50 units
          initialQuantities[item.productName] = 50 - (item.qty || 0);
        });
        setReorderQuantities(initialQuantities);

      } catch (err) {
        console.error("Order Load Error:", err.message);
        setStatusMessage(`❌ Failed to load replenishment requirements: ${err.message}`);
      } finally {
        setLoading(false);
      }
    }
    fetchDepletedStock();
  }, []);

  // Handle live modification of reorder amounts in input fields
  const handleQuantityChange = (productName, value) => {
    const val = parseInt(value) || 0;
    setReorderQuantities(prev => ({
      ...prev,
      [productName]: val
    }));
  };

  // --- 📥 GENERATE PURCHASE ORDER PDF FUNCTION ---
  const generatePurchaseOrderPDF = () => {
    // Filter down to only items that have an active reorder quantity greater than 0
    const activeReorderItems = replenishList.filter(
      item => reorderQuantities[item.productName] > 0
    );

    if (activeReorderItems.length === 0) {
      return alert("No items have quantities set for reorder! Adjust the cards below.");
    }

    try {
      const doc = new jsPDF();
      const poNumber = `PO-${Math.floor(100000 + Math.random() * 900000)}`;
      const currentDate = new Date().toLocaleDateString();

      // 1. PO Header Styling
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(197, 48, 48); // Warning/Alert dark red branding color
      doc.text("PURCHASE ORDER REPLENISHMENT", 14, 20);

      // 2. Meta Info Metadata Block (Right Aligned)
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      doc.text(`PO Number: ${poNumber}`, 145, 16);
      doc.text(`Date Issued: ${currentDate}`, 145, 22);

      // Divider Line
      doc.setDrawColor(226, 232, 240);
      doc.line(14, 28, 196, 28);

      // 3. Document Summary Details
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(50);
      doc.text("INVENTORY DEFICIT METRICS SUMMARY:", 14, 38);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Total SKU Outages Pending Restock: ${activeReorderItems.length} lines`, 14, 45);
      doc.text(`Target Stock Buffer Parameter: <= ${REPLENISH_THRESHOLD} units`, 14, 51);

      // 4. Transform Map Data into Matrix for autoTable
      const tableHeaders = [["Sl.", "Product Item Name / Description", "Current Warehouse Stock", "Requested Reorder Volume"]];
      const tableRows = activeReorderItems.map((item, index) => [
        index + 1,
        item.productName,
        `${item.qty || 0} units`,
        `${reorderQuantities[item.productName]} units` // Custom value typed into input card
      ]);

      // 5. Build Table Structure
      autoTable(doc, {
        head: tableHeaders,
        body: tableRows,
        startY: 58,
        theme: 'striped',
        headStyles: { fillColor: [197, 48, 48], fontSize: 10, halign: 'left' },
        styles: { fontSize: 10, font: 'helvetica' },
        columnStyles: {
          0: { cellWidth: 15 },
          1: { cellWidth: 100 },
          2: { cellWidth: 40 },
          3: { cellWidth: 35 }
        }
      });

      // 6. Footer Disclaimer Sign-off
      const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 150;
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(120);
      doc.text("Note: This document was auto-generated by the POS Inventory Replenishment module based on active low-stock constraints.", 14, finalY);

      // 7. Save Target Download Trigger
      doc.save(`PurchaseOrder_${poNumber}.pdf`);
    } catch (pdfError) {
      console.error("PO PDF Generation failed:", pdfError);
      alert(`Could not compile PDF: ${pdfError.message}`);
    }
  };

  if (loading) {
    return (
      <div style={{ padding: '40px 0', textAlign: 'center', color: 'var(--aqua-dark)' }}>
        <p style={{ fontWeight: '500', fontSize: '16px' }}>🔄 Analyzing warehouse inventory metrics...</p>
      </div>
    );
  }

  return (
    <div style={{ width: '100%' }}>
      
      {/* HEADER BAR AND MASTER PDF BUTTON */}
      <div className="premium-card-red" style={{ borderLeft: '4px solid var(--red)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '20px', marginBottom: '30px' }}>
        <div>
          <h2 className="heading-gradient-red" style={{ margin: '0 0 6px 0', fontSize: '24px' }}>🚨 Interactive Replenishment Board</h2>
          <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: '14px' }}>
            Modify requested replenishment sizes inside each item card below, then export the master purchase order.
          </p>
        </div>
        
        <button 
          onClick={generatePurchaseOrderPDF}
          disabled={replenishList.length === 0}
          className="premium-btn-red"
          style={{
            opacity: replenishList.length === 0 ? 0.5 : 1,
            cursor: replenishList.length === 0 ? 'not-allowed' : 'pointer',
            padding: '12px 24px',
            fontSize: '15px'
          }}
        >
          📥 Export Purchase Order PDF
        </button>
      </div>

      {replenishList.length === 0 ? (
        <div className="premium-card" style={{ borderLeft: '4px solid var(--aqua)', padding: '30px', textAlign: 'center', color: 'var(--aqua-dark)', fontWeight: '600', fontSize: '16px' }}>
          ✅ All items are healthy and securely stocked above safety buffer settings!
        </div>
      ) : (
        /* INTERACTIVE CARDS FLEX GRID LAYOUT */
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '20px' }}>
          {replenishList.map((item) => {
            const isOutOfStock = (item.qty || 0) === 0;
            const currentOrderQty = reorderQuantities[item.productName] || 0;
            const CardClass = isOutOfStock ? 'premium-card-red' : 'premium-card';
            const accentColor = isOutOfStock ? 'var(--red)' : 'var(--aqua)';

            return (
              <div 
                key={item.productName}
                className={CardClass}
                style={{
                  borderLeft: `4px solid ${accentColor}`,
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                  padding: 0,
                  overflow: 'hidden'
                }}
              >
                {/* Card Top Block */}
                <div style={{ padding: '20px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                    <span style={{
                      padding: '3px 10px',
                      borderRadius: '12px',
                      fontSize: '11px',
                      fontWeight: '600',
                      color: '#fff',
                      background: isOutOfStock ? 'var(--red)' : 'var(--aqua)',
                      textTransform: 'uppercase',
                      letterSpacing: '0.5px'
                    }}>
                      {isOutOfStock ? 'Out of Stock' : 'Low Stock Warning'}
                    </span>
                    <span style={{ fontSize: '13px', color: 'var(--text-muted)', fontWeight: '600' }}>
                      Rate: Rs. {item.rate}
                    </span>
                  </div>

                  <h4 style={{ margin: '0 0 12px 0', fontSize: '16px', color: 'var(--text-dark)', fontWeight: '600', lineHeight: '1.4' }}>
                    {item.productName}
                  </h4>

                  <div style={{ background: 'var(--bg-accent)', padding: '10px 12px', borderRadius: '6px', fontSize: '13px', color: 'var(--text-muted)' }}>
                    Current Warehouse Inventory: <strong style={{ color: isOutOfStock ? 'var(--red-dark)' : 'var(--aqua-dark)' }}>{item.qty || 0} units</strong>
                  </div>
                </div>

                {/* Card Lower Interactive Input Block */}
                <div style={{ padding: '15px 20px', background: 'var(--bg-accent)', borderTop: '1px solid var(--border-light)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '10px' }}>
                  <label style={{ fontSize: '13px', fontWeight: '600', color: 'var(--text-dark)', whiteSpace: 'nowrap' }}>
                    Reorder Quantity:
                  </label>
                  <input 
                    type="number"
                    min="0"
                    value={currentOrderQty}
                    onChange={(e) => handleQuantityChange(item.productName, e.target.value)}
                    className={isOutOfStock ? 'premium-input-red' : 'premium-input'}
                    style={{
                      width: '90px',
                      padding: '6px',
                      textAlign: 'center',
                      fontWeight: '700',
                      fontSize: '14px',
                      outline: 'none',
                      background: '#fff'
                    }}
                  />
                </div>
              </div>
            );
          })}
        </div>
      )}

      {statusMessage && (
        <div className="premium-card" style={{ marginTop: '20px', padding: '12px', textAlign: 'center', color: 'var(--text-muted)', borderLeft: '4px solid var(--border-light)' }}>
          {statusMessage}
        </div>
      )}
    </div>
  );
};

export default Order;